# ~/.bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Source aliases
if [ -f $HOME/.aliases ]; then
    . $HOME/.aliases
fi

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# Change the prompt
PS1="\e[1;15m\w \e[1;91m>>  \e[0m"


# Set vim-mode of gvim  as standard editor
export EDITOR="gvim -v"
export VISUAL="$EDITOR"

# don't save duplicates in bash history, delete duplicates except newest
export HISTCONTROL=ignoreboth:erasedups

export CHEATCOLORS=true


eval "$(thefuck --alias)"

