#!/bin/bash




# checking for Inbox Zero
inboxzero

# Backing up
#echo "Backing up Files"
#pmount /dev/sdb1
#cd /dev/sdb1

#homeFolderFiles=ls ~/

#cp -r -u /dev/sdb1/0.Backup/ $homeFolderFiles
#pumount /dev/sdb1
echo


# Cleaning up Temp Files
rm -rf ~/.cache/thumbnails/*

# Running upgrade
echo "Updating System"
sudo dnf upgrade
echo

# decide between poweroff and shutdown
while true; do
 read -p "Do you want to suspend or shutdown the system? [sus/shu] " ans
 case $ans in
  sus) echo "suspending..."; sysus;;
  shu) echo "shutting down..."; echo "shu";;
 esac
done

exit

