#!/bin/bash
# shellcheck disable=SC2162

# checking for Inbox Zero

#function doItNow
function supposedToBe() {
  while true; do
    read -p "$1 [y/N] " yn
    case $yn in
      [Yy] ) echo; break;;
      [Nn] ) echo "You better clean ${2-them} out then."; echo;;
    esac
  done
  return 0
}

# 0.Inbox
inboxFiles=$(find ~/0.Inbox/ -not \( -path '*/.*' -o -path '*/' \) -printf ' * %P\n')
fileCount=$(echo "$inboxFiles" | wc -l)
if [[ $fileCount != 0 ]] ; then
  echo -e "There are $fileCount files in 0.Inbox:\n$inboxFiles"
  supposedToBe "Are they supposed to be there?"
fi

# Camera Uploads
cameraUploads=$(find ~/Camera\ Uploads/ -not \( -path '*/.*' -o -path '*/' \) | wc -l)
if [[ ! $cameraUploads == 0 ]] ; then
 echo "There are unsorted photos in Camera Uploads."
  supposedToBe "Are they supposed to be there?"
fi

# Firefox Bookmarks
supposedToBe "Did you clean up the Firefox Bookmarks?"

# Home Folder
supposedToBe "Did you clean up your home directory?" "it"
 

# Backing up
#echo "Backing up Files"
#pmount /dev/sdb1
#cd /dev/sdb1

#homeFolderFiles=ls ~/

#cp -r -u /dev/sdb1/0.Backup/ $homeFolderFiles
#pumount /dev/sdb1
echo


# Cleaning up Temp Files
rm -rf ~/.cache/thumbnails/*

# Running upgrade
echo "Updating System"
sudo dnf upgrade
echo

# decide between poweroff and shutdown
while true; do
 read -p "Do you want to suspend or shutdown the system? [sus/shu] " ans
 case $ans in
  sus) echo "suspending..."; sysus;;
  shu) echo "shutting down..."; echo "shu";;
 esac
done

exit

# systemctl suspend
# systemctl poweroff

