#!/bin/bash

# Name: Extract
# Brief: Extracts an archive whatever its extension (well, it can do tar, rar and zip)


# get the archive
archive=$1

# extract based on extension
case "$archive" in
 *.tar.bz2)
    echo "Extracting tar..."
    tar -xjvf "$archive";;
 *.tar.gz)
    echo "Extracting tar..."
    tar -xzvf "$archive";;
 *.rar)
    echo "Extracting rar..."
    unrar e "$archive";;
 *.zip)
    echo "Extracting zip..."
    unzip "$archive";;
esac 

exit

