#!/bin/bash
# shellcheck disable=SC2162



# asks if location was cleaned up/is supposed to be that way
function supposedToBe() {
  read -p "$1 [y/N] " yn
  while true; do
    case $yn in
      [Yy]) break;;
      [Nn]) echo "You better do it now then."; read -p "Done? [y/N] " yn;;
      * ) read -p "Are you done or not? [y/N] " yn;;
    esac
  done
  echo
  return 0
}


# Code Commits
supposedToBe "Did you commit all code?"


# 0.Inbox
inboxFiles=$(find ~/0.Inbox/ -not \( -path '*/.*' -o -path '*/' \) -printf ' * %P\n')
fileCount=$(echo "$inboxFiles" | wc -l)
if [[ $fileCount != 0 ]] ; then
  echo -e "There are $fileCount files in 0.Inbox:\n$inboxFiles"
  supposedToBe "Sure you shouldn't clean them out?"
fi

# Camera Uploads
cameraUploads=$(find ~/New\ Photos/ -not \( -path '*/.*' -o -path '*/' \) | wc -l)
if [[ ! $cameraUploads == 0 ]] ; then
  echo "There are new photos."
  supposedToBe "Sure you shouldn't move them into the Photo folder?"
fi

# Firefox Bookmarks
supposedToBe "Did you clean up the Firefox Bookmarks?"

# Home Folder
supposedToBe "Did you clean up your home directory?"

exit

