#!/bin/bash

# Name: System Suspension
# Brief: Suspends the systems and unmounts drives beforehand if necessary


# unmmount drives
aumount
# exit script, then suspend the machine
exit & systemctl suspend

