#!/bin/bash

# Name: Wallpaper Switcher
# Brief: Switches the wallpaper depending on the time of day


# get time of day
tOD=$(date +%H%M)
tOD=${tOD#0}

# determine current actual phase of the day
if [[ $tOD -lt 600 || $tOD -ge 1900 ]] ; then
	phase="night"
elif [[ $tOD -ge 730 && $tOD -lt 1700 ]] ; then
	phase="day"
else
	phase="twilight"
fi

# set wallpaper
DISPLAY=:0 feh --bg-fill "/home/solvi/i.dotfiles-repo/wall-${phase}.jpg" 

exit

