#!/bin/bash

# Name: Wallpaper Switcher
# Brief: Switches the wallpaper depending on the time of day


# get time of day
tOD=$(date +%H%M)

# determine current actual phase of the day
if [[ tOD -lt 0600 || tOD -ge 1900 ]] ; then
	phase="night"
elif [[ tOD -ge 0730 && tOD -lt 1700 ]] ; then
	phase="day"
else
	phase="twilight"
fi

# set wallpaper
feh --bg-fill "/home/solvi/i.dotfiles-repo/wall-${phase}.jpg" 

exit

